### ISSUE TITLE
Cannot run with .TFlite with batch size > 1.

### ISSUE THREAD

**Issue by boyapdao** [surendramaran/YOLOv8-TfLite-Object-Detector#22]
I have successfully run the source with the TFlite file with the following parameters, input Shape [1, 640, 640, 3] and output Shape [1, 10, 8400].
But after trying with another file with input Shape [4, 320, 320, 3], output Shape [4, 84, 2100] parameters it crashed.
Following is the error in logcat:
```
FATAL EXCEPTION: pool-2-thread-1
Process: com.surendramaran.yolov8tflite, PID: 9281
java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (inputs_0) with 4915200 bytes from a Java Buffer with 1228800 bytes.
	at org.tensorflow.lite.TensorImpl.throwIfSrcShapeIsIncompatible(TensorImpl.java:426)
	at org.tensorflow.lite.TensorImpl.setTo(TensorImpl.java:150)
	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:260)
	at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:101)
	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:95)
	at org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:94)
	at org.tensorflow.lite.Interpreter.run(Interpreter.java:95)
	at com.surendramaran.yolov8tflite.Detector.detect(Detector.kt:135)
	at com.surendramaran.yolov8tflite.MainActivity.bindCameraUseCases$lambda$7(MainActivity.kt:130)
	at com.surendramaran.yolov8tflite.MainActivity.$r8$lambda$SwMDthyT4p6a561NxBZ96bJyetY(Unknown Source:0)
	at com.surendramaran.yolov8tflite.MainActivity$$ExternalSyntheticLambda6.analyze(D8$$SyntheticClass:0)
	at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:527)
	at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda2.analyze(D8$$SyntheticClass:0)
	at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:286)
	at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```
I understand that with the second file, the batch size has changed from 1 -> 4. How should I edit the code to be able to run with the second file?
First file parameters:
![first file parameters](https://github.com/user-attachments/assets/4177359d-9678-40ab-8d73-c47d21dbea9a)

2nd file parameters: 
![image](https://github.com/user-attachments/assets/7053f2f0-47fc-4d56-addd-a3fec53473fa)

first file: [2806_int8.tflite.zip](https://github.com/user-attachments/files/16494198/2806_int8.tflite.zip)
second file: [yolov8n_float16_batch_1.tflite.zip](https://github.com/user-attachments/files/16494206/yolov8n_float16_batch_1.tflite.zip)
label: [labels.txt](https://github.com/user-attachments/files/16494219/labels.txt)

**Comment by surendramaran** [comment]
But is it really yolov8?

**Comment by boyapdao** [comment]
Yes, it's yolov8.
first file: [2806_int8.tflite.zip](https://github.com/user-attachments/files/16494198/2806_int8.tflite.zip)
second file: [yolov8n_float16_batch_1.tflite.zip](https://github.com/user-attachments/files/16494206/yolov8n_float16_batch_1.tflite.zip)
label: [labels.txt](https://github.com/user-attachments/files/16494219/labels.txt)

**Comment by surendramaran** [comment]
I haven't seen this type before, can you tell me how you got this model?

**Comment by boyapdao** [comment]
Here is a model a team member sent me, he explained that changing the batch size from 1 -> 4 means it will analyze the object based on 4 images at a time instead of just 1. image. The goal is to test the time delay of the model with batch size 4 compared to batch size 1.
